[book]
title = "Standard library developers Guide"
authors = ["the rust-lang authors"]
description = "Guide for standard library developers"
language = "en"
multilingual = false
src = "./src"

[build]
create-missing = true

[rust]
edition = "2018"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.linkcheck]

[output.html]
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/rust-lang/std-dev-guide"
edit-url-template = "https://github.com/rust-lang/std-dev-guide/edit/master/{path}"

[output.html.redirect]
"/feature-lifecycle/stabilization.html" = "/development/stabilization.html"
