[book]
title = "Standard library developers Guide"
authors = ["the rust-lang authors"]
description = "Guide for standard library developers"
language = "en"
multilingual = false
src = "./src"

[build]
create-missing = false

[rust]
edition = "2018"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.linkcheck]

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/rust-lang/std-dev-guide"
git-repository-icon = "fa-github"
